set nocompatible

filetype off
"{{{ PLUGIN
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'vim-scripts/UltiSnips'
Plugin 'vim-airline/vim-airline'
Plugin 'godlygeek/csapprox'
Plugin 'sheerun/vim-polyglot'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'tpope/vim-surround'
Plugin 'moll/vim-bbye'
Plugin 'Valloric/YouCompleteMe', {
            \ 'build' : {
            \ 'unix': './install.sh --clang-completer --system-libclang --omnisharp-completer',
            \ 'mac': './install.sh --clang-completer --system-libclang --omnisharp-completer'
            \ }
        \ }

" Choose a theme
Plugin 'tomasr/molokai'
Plugin 'morhetz/gruvbox'

call vundle#end()
filetype plugin indent on

"}}} END PLUGIN
"
"{{{ CUSTOM MAPPINGS
let mapleader = ","

"edit vimrc
nmap <leader>sv :source ~/.vimrc<cr>
nmap <leader>ev :vsplit ~/.vimrc<cr>

" window settings
" open new windows to the right or bottom
set splitright
set splitbelow

" change with movement keys
nmap <leader>h <C-W>h<cr>
nmap <leader>l <C-W>l<cr>
nmap <leader>j <C-W>j<cr>
nmap <leader>k <C-W>k<cr>

" cycle through buffers
nmap <leader>z :bprevious<cr>
nmap <leader>x :bnext<cr>

" write and quit
"nmap <leader>q :quit<cr>
nmap <leader>q :Bdelete<cr>
nmap <leader>w :write<cr>

"clear search highlight
nmap <leader><Space> :nohlsearch<cr>

"ctags
nmap <leader>n :cnext<cr>
nmap <leader>N :cprevious<cr>

"custom retab function (autogenerated)
nmap <leader>r :%s/\t/    /g<cr>

"NERDtree
nmap <leader>nn :NERDTreeToggle<cr>
nnoremap <leader>nf :NERDTreeFind<cr>

"toggle folds
nmap <Space> za

"}}} END CUSTOM MAPPINGS

"{{{ SETTINGS
set mouse=a

syntax enable
set t_Co=256
" Choose a theme
colorscheme molokai
"colorscheme gruvbox

set cursorline

set showcmd

set nowrap

set incsearch

set foldmethod=syntax foldnestmax=10

" tab behavior (spoiler alert: it's 4 spaces)
set tabstop=4 shiftwidth=4 softtabstop=4
set expandtab

set number relativenumber

set list listchars=tab:>~

set scrolloff=10

set autoindent smartindent
"}}} END SETTINGS

"{{{ AUTOCMD SETTINGS
"make the vimrc fold by marker

"}}} END AUTOCMD SETTINGS
