set nocompatible

filetype off
"{{{ PLUGIN
" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdcommenter'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'nelstrom/vim-visual-star-search'
Plugin 'tommcdo/vim-lion'
Plugin 'vim-scripts/UltiSnips'
Plugin 'vim-scripts/abolish.vim'
Plugin 'kana/vim-repeat'
Plugin 'vim-airline/vim-airline'
Plugin 'godlygeek/csapprox'
Plugin 'sheerun/vim-polyglot'
Plugin 'ntpeters/vim-better-whitespace'
Plugin 'tpope/vim-surround'
Plugin 'moll/vim-bbye'
Plugin 'tangledhelix/vim-kickstart'
Plugin 'Valloric/YouCompleteMe', {
            \ 'build' : {
            \ 'unix': './install.sh --clang-completer --system-libclang --omnisharp-completer',
            \ 'mac': './install.sh --clang-completer --system-libclang --omnisharp-completer'
            \ }
        \ }

" Choose a theme
Plugin 'tomasr/molokai'
Plugin 'morhetz/gruvbox'

call vundle#end()
filetype plugin indent on

"}}} END PLUGIN
"
"{{{ PLUGIN CONFIG
"Start interactive EasyAlign in visual mode
xmap ga <Plug>(EasyAlign)
"Start interactive EasyAlign for motion/text object
nmap ga <Plug>(EasyAlign)

let g:lion_squeeze_spaces = 1

let g:sysnastic_python_checkers = ['pylint', 'flake8']
"}}} END PLUGIN CONFIG
"
"{{{ CUSTOM MAPPINGS
let mapleader = ","

"edit vimrc
nmap <leader>sv :source ~/.vimrc<cr>
nmap <leader>ev :vsplit ~/.vimrc<cr>

" window settings
" open new windows to the right or bottom
set splitright
set splitbelow

" change window with movement keys
nmap <leader>h <C-W>h
nmap <leader>l <C-W>l
nmap <leader>j <C-W>j
nmap <leader>k <C-W>k

" cycle through buffers
nmap <leader>z :bprevious<cr>
nmap <leader>x :bnext<cr>

" write and quit
"nmap <leader>q :quit<cr>
nmap <leader>q :Bdelete<cr>
nmap <leader>w :write<cr>

"clear search highlight
nmap <leader><Space> :nohlsearch<cr>

"ctags
nmap <leader>n :cnext<cr>
nmap <leader>N :cprevious<cr>

"custom retab function (autogenerated)
nmap <leader>r :%s/\t/    /g<cr>

"NERDtree
nmap <leader>nn :NERDTreeToggle<cr>
nnoremap <leader>nf :NERDTreeFind<cr>

"toggle folds
nmap <Space> za

"send yank buffer to tmux
nmap <leader>y :call system("tmux set-buffer ", @0)<cr>

"}}} END CUSTOM MAPPINGS

"{{{ SETTINGS
set shell=/usr/bin/zsh
set mouse=a

syntax enable
set t_Co=256
" Choose a theme
colorscheme molokai
"colorscheme gruvbox

set cursorline

set showcmd

set nowrap

set incsearch

set foldmethod=syntax foldnestmax=10

" tab behavior (spoiler alert: it's 4 spaces)
set tabstop=4 shiftwidth=4 softtabstop=4
set expandtab

set number relativenumber

set list listchars=tab:>~

set scrolloff=10

set autoindent smartindent
"}}} END SETTINGS

"{{{ AUTOCMD SETTINGS
"make the vimrc fold by marker
augroup VIM
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker foldlevelstart=999 foldminlines=0
augroup END
augroup XML
    autocmd!
    autocmd FileType xml setlocal foldmethod=indent foldlevelstart=999 foldminlines=0
augroup END

" No need for smartintent in python, esp. since it destroys comment
" indentation
au! FileType python setl nosmartindent

"}}} END AUTOCMD SETTINGS
